const archetypes=[
{id:'quiet-heirloom',name:'Quiet Heirloom',description:'restrained, soft, table-safe, closest to the preferred 04 direction',bias:{belly:.48,waist:.30,foot:.52,lip:.38,height:.52,shoulder:.42,quiet:.72}},
{id:'soft-tulip',name:'Soft Tulip',description:'more filiżanka, more premium rim, still controlled',bias:{belly:.42,waist:.48,foot:.42,lip:.72,height:.55,shoulder:.56,quiet:.44}},
{id:'low-table-cup',name:'Low Table Cup',description:'low, broad, stable, table-first; promising for children',bias:{belly:.56,waist:.26,foot:.50,lip:.42,height:.30,shoulder:.40,quiet:.62}},
{id:'noble-belly',name:'Noble Belly',description:'warm family body with controlled fullness',bias:{belly:.78,waist:.36,foot:.44,lip:.44,height:.48,shoulder:.55,quiet:.46}},
{id:'footed-classic',name:'Footed Classic',description:'stronger foot, stronger table shadow, more classic table culture',bias:{belly:.42,waist:.34,foot:.82,lip:.46,height:.48,shoulder:.38,quiet:.55}},
{id:'modern-heirloom',name:'Modern Heirloom',description:'cleaner, contemporary, one subtle signature gesture',bias:{belly:.34,waist:.30,foot:.46,lip:.36,height:.58,shoulder:.34,quiet:.80}},
{id:'heirloom-hero',name:'Heirloom Hero',description:'more soul, more tension, kept below fashion-object territory',bias:{belly:.58,waist:.52,foot:.66,lip:.58,height:.50,shoulder:.58,quiet:.35}}
];
const critiqueTags=['has soul','dead','too camping','too ordinary','too fashion','good foot','bad foot','good rim','rim too loud','good waist','too bowl','too mug','premium','warm family','child dignified','120 toy risk','440 bucket risk','more like this'];
const K={decisions:'shapeHunt.v2.decisions',tags:'shapeHunt.v2.tags',history:'shapeHunt.v2.history',shapes:'shapeHunt.v2.shapes',settings:'shapeHunt.v2.settings'};
const state={seed:1247,shapes:[],focusIndex:0,view:'gallery',decisions:read(K.decisions,{}),tags:read(K.tags,{}),history:read(K.history,[]),settings:{sort:'recommended',showRejected:false,density:600,archetype:'all',...read(K.settings,{})}};
const $=(q,r=document)=>r.querySelector(q); const $$=(q,r=document)=>[...r.querySelectorAll(q)];
function read(k,f){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}}
function write(k,v){localStorage.setItem(k,JSON.stringify(v))}
function save(){write(K.decisions,state.decisions);write(K.tags,state.tags);write(K.history,state.history.slice(-1000));write(K.settings,state.settings)}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))} function lerp(a,b,t){return a+(b-a)*t} function rnd(v,p=0){const m=10**p;return Math.round(v*m)/m}
function rng(seed){return function(){let t=seed+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function jit(r,a=1){return(r()-.5)*a} function pick(a,r){return a[Math.floor(r()*a.length)]}
function makeShape(id,arch,r,over={}){const b=arch.bias;return enrich({id,archetypeId:arch.id,archetypeName:arch.name,archetypeDescription:arch.description,height:clamp(lerp(74,90,b.height)+jit(r,16),62,104),base:clamp(lerp(66,84,b.foot)+jit(r,14),56,92),rim:clamp(lerp(90,112,b.lip)+jit(r,18),82,126),belly:clamp(b.belly+jit(r,.38),.04,1),waist:clamp(b.waist+jit(r,.38),0,1),foot:clamp(b.foot+jit(r,.38),0,1),lip:clamp(b.lip+jit(r,.38),.02,1),shoulder:clamp(b.shoulder+jit(r,.44),.02,1),quiet:clamp(b.quiet+jit(r,.40),.05,1),...over})}
function enrich(s){const hToRim=s.height/Math.max(1,s.rim),stability=s.base/Math.max(1,s.height),table=scoreTable(s),soul=scoreSoul(s),camp=scoreCamping(s),fam=scoreFamily(s);return {...s,hToRim:rnd(hToRim,2),stability:rnd(stability,2),tableScore:rnd(table,2),soulScore:rnd(soul,2),campingRisk:rnd(camp,2),familyRisk:rnd(fam,2),massProxy:Math.round(s.height*(s.base+s.rim)*.0105+s.foot*12+s.belly*10+s.lip*4),recommendation:rnd(table*.34+soul*.36+(1-camp)*.20+(1-fam)*.10,3)}}
function scoreTable(s){const low=1-Math.min(1,Math.abs(s.height/Math.max(1,s.rim)-.82)/.38),foot=s.foot,stab=clamp((s.base/Math.max(1,s.height)-.70)/.40,0,1),quiet=1-Math.abs(s.quiet-.62);return clamp(low*.35+foot*.24+stab*.26+quiet*.15,0,1)}
function scoreSoul(s){const waist=1-Math.abs(s.waist-.42)/.42,foot=1-Math.abs(s.foot-.62)/.60,rim=1-Math.abs(s.lip-.52)/.52,belly=1-Math.abs(s.belly-.56)/.56,pen=s.quiet>.86?(s.quiet-.86)*1.8:0;return clamp(waist*.28+foot*.24+rim*.18+belly*.22+(1-pen)*.08,0,1)}
function scoreCamping(s){const weak=clamp((.34-s.foot)/.34,0,1),cyl=clamp((.18-Math.abs((s.rim-s.base)/Math.max(1,s.rim)))/.18,0,1),tall=clamp((s.height/Math.max(1,s.rim)-1.02)/.35,0,1),dead=clamp((.20-s.waist)/.20,0,1)*clamp((.30-s.belly)/.30,0,1);return clamp(weak*.35+cyl*.24+tall*.22+dead*.19,0,1)}
function scoreFamily(s){const child=clamp((s.lip-.76)/.24,0,1)*.35+clamp((s.waist-.68)/.32,0,1)*.35,large=clamp((s.belly-.78)/.22,0,1)*.42+clamp((s.rim-116)/12,0,1)*.38,inst=clamp((.70-s.base/Math.max(1,s.height))/.20,0,1);return clamp(child+large+inst*.25,0,1)}
function generateBatch(n=state.settings.density){const r=rng(state.seed++),out=[];for(let i=0;i<n;i++)out.push(makeShape(`S${String(i+1).padStart(4,'0')}`,archetypes[i%archetypes.length],r));out.unshift(makeShape('A001_Quiet_04_Evolved',archetypes[0],r,{height:82,base:76,rim:102,belly:.48,waist:.34,foot:.66,lip:.42,shoulder:.36,quiet:.72}),makeShape('A002_Table_Tulip',archetypes[1],r,{height:82,base:74,rim:104,belly:.42,waist:.48,foot:.56,lip:.64,shoulder:.54,quiet:.48}),makeShape('A003_Low_Noble',archetypes[2],r,{height:76,base:78,rim:100,belly:.56,waist:.26,foot:.62,lip:.40,shoulder:.34,quiet:.65}),makeShape('A004_Footed_Signature',archetypes[4],r,{height:82,base:78,rim:100,belly:.42,waist:.34,foot:.84,lip:.44,shoulder:.36,quiet:.58}));state.shapes=out;persistShapes();state.focusIndex=0;render();toast(`Generated ${out.length} silhouettes`)}
function persistShapes(){try{write(K.shapes,state.shapes)}catch{}}
function restoreShapes(){const s=read(K.shapes,[]);if(Array.isArray(s)&&s.length){state.shapes=s.map(enrich);return true}return false}
function moreLike(shape,n=160){const r=rng(Math.floor(Math.random()*999999)),arch=archetypes.find(a=>a.id===shape.archetypeId)||archetypes[0],out=[];for(let i=0;i<n;i++){const st=i<n*.55?.18:.28;out.push(makeShape(`M${shape.id}_${String(i+1).padStart(3,'0')}`,arch,r,{height:clamp(shape.height+jit(r,20*st),60,106),base:clamp(shape.base+jit(r,22*st),54,94),rim:clamp(shape.rim+jit(r,24*st),80,128),belly:clamp(shape.belly+jit(r,.52*st),.02,1),waist:clamp(shape.waist+jit(r,.52*st),0,1),foot:clamp(shape.foot+jit(r,.56*st),0,1),lip:clamp(shape.lip+jit(r,.56*st),.02,1),shoulder:clamp(shape.shoulder+jit(r,.56*st),.02,1),quiet:clamp(shape.quiet+jit(r,.44*st),.05,1)}))}setDecision(shape.id,{moreLike:(state.decisions[shape.id]?.moreLike||0)+1,saved:true});addHistory(shape.id,'more-like-this');state.shapes=out.concat(state.shapes.filter(s=>s.id!==shape.id));persistShapes();state.view='gallery';closeFocus();render();toast(`Generated ${n} variations around ${shape.id}`)}
function familyAdapt(shape,ml){const r={120:{height:.63,base:.82,rim:.78,belly:.70,waist:.50,foot:1.18,lip:.72,shoulder:.68},240:{height:.82,base:.93,rim:.91,belly:.84,waist:.70,foot:1.08,lip:.86,shoulder:.84},330:{height:1,base:1,rim:1,belly:1,waist:1,foot:1,lip:1,shoulder:1},440:{height:1.15,base:1.10,rim:1.10,belly:1.05,waist:.94,foot:.96,lip:1.02,shoulder:1.02}}[ml];return enrich({...shape,id:`${shape.id}_${ml}`,height:shape.height*r.height,base:shape.base*r.base,rim:shape.rim*r.rim,belly:clamp(shape.belly*r.belly,0,1),waist:clamp(shape.waist*r.waist,0,1),foot:clamp(shape.foot*r.foot,0,1),lip:clamp(shape.lip*r.lip,0,1),shoulder:clamp(shape.shoulder*r.shoulder,0,1)})}
function geom(shape,ml=330){const f=ml===330?shape:familyAdapt(shape,ml),h=f.height,baseR=f.base/2,rimR=f.rim/2,footPull=lerp(1,7.6,f.foot),belly=lerp(.6,9.2,f.belly),waist=lerp(0,6.1,f.waist),lip=lerp(.4,6.8,f.lip),sh=lerp(.1,5.6,f.shoulder);const y0=0,y1=h*.075,y2=h*.19,y3=h*lerp(.38,.48,f.waist),y4=h*.68,y5=h*.90,y6=h;const r0=baseR,r1=Math.max(9,baseR-footPull),r2=baseR+lerp(.6,4.5,f.foot),r3=lerp(baseR,rimR,.42)+belly-waist,r4=lerp(baseR,rimR,.70)+belly*.55+sh,r5=rimR+lip*.28,r6=rimR+lip;return{h,p:{y0,y1,y2,y3,y4,y5,y6,r0,r1,r2,r3,r4,r5,r6}}}
function path(shape,opt={}){const ml=opt.familySize||330,scale=opt.scale||1,{h,p}=geom(shape,ml),cx=90,top=opt.top||16,k=2.25*scale;const P=(r,y)=>`${(cx+r*k).toFixed(1)},${(top+(h-y)*k).toFixed(1)}`,L=(r,y)=>`${(cx-r*k).toFixed(1)},${(top+(h-y)*k).toFixed(1)}`;return[`M ${P(p.r0,p.y0)}`,`C ${P(p.r1,p.y0+h*.03)} ${P(p.r1,p.y1)} ${P(p.r1,p.y1)}`,`C ${P(p.r2,p.y1+h*.05)} ${P(p.r2,p.y2)} ${P(p.r2,p.y2)}`,`C ${P(p.r3,p.y2+h*.10)} ${P(p.r3,p.y3-h*.04)} ${P(p.r3,p.y3)}`,`C ${P(p.r4,p.y3+h*.12)} ${P(p.r4,p.y4-h*.04)} ${P(p.r4,p.y4)}`,`C ${P(p.r5,p.y4+h*.10)} ${P(p.r5,p.y5)} ${P(p.r5,p.y5)}`,`C ${P(p.r6,p.y5+h*.04)} ${P(p.r6,p.y6)} ${P(p.r6,p.y6)}`,`L ${L(p.r6,p.y6)}`,`C ${L(p.r6,p.y6)} ${L(p.r6,p.y5+h*.04)} ${L(p.r5,p.y5)}`,`C ${L(p.r5,p.y5)} ${L(p.r5,p.y4+h*.10)} ${L(p.r4,p.y4)}`,`C ${L(p.r4,p.y4-h*.04)} ${L(p.r4,p.y3+h*.12)} ${L(p.r3,p.y3)}`,`C ${L(p.r3,p.y3-h*.04)} ${L(p.r3,p.y2+h*.10)} ${L(p.r2,p.y2)}`,`C ${L(p.r2,p.y2)} ${L(p.r2,p.y1+h*.05)} ${L(p.r1,p.y1)}`,`C ${L(p.r1,p.y1)} ${L(p.r1,p.y0+h*.03)} ${L(p.r0,p.y0)}`,'Z'].join(' ')}
function svg(shape,opt={}){const vb=opt.large?'0 0 180 254':'0 0 180 230',ty=opt.large?235:222,ml=opt.familySize||330,ad=ml===330?shape:familyAdapt(shape,ml),cap=opt.large?`<text x="90" y="248" text-anchor="middle" class="svg-caption">H ${Math.round(ad.height)} · base ${Math.round(ad.base)} · rim ${Math.round(ad.rim)}</text>`:'';return`<svg viewBox="${vb}" role="img" aria-label="${shape.id} silhouette"><line x1="28" x2="152" y1="${ty}" y2="${ty}" class="table-line"/><path d="${path(shape,opt)}" fill="currentColor"/>${cap}</svg>`}
function cardHTML(s){const d=state.decisions[s.id]||{},chips=[];if(s.campingRisk>.55)chips.push('camping risk');if(s.soulScore>.72)chips.push('soul');if(s.tableScore>.72)chips.push('table');if(s.familyRisk>.55)chips.push('family risk');return`<div class="shape-art">${svg(s)}</div><div class="shape-meta"><div><b>${s.id}</b><br><span>${s.archetypeName}</span></div><div class="card-actions"><button class="icon-btn" title="Good" data-act="good">＋</button><button class="icon-btn" title="Bad" data-act="bad">−</button><button class="icon-btn" title="Save" data-act="save">♡</button><button class="icon-btn" title="More like this" data-act="more">⋯</button></div></div><div class="score-row"><span>${Math.round(s.height)}H</span><span>${Math.round(s.base)}B</span><span>${Math.round(s.rim)}R</span><span>${Math.round(s.recommendation*100)}</span></div>${chips.length?`<div class="card-chips">${chips.map(c=>`<span>${c}</span>`).join('')}</div>`:''}${d.saved?'<div class="saved-flag">saved</div>':''}`}
function renderCard(s,index){const d=state.decisions[s.id]||{},el=document.createElement('article');el.className='shape-card';el.dataset.state=d.rating||'';el.dataset.saved=d.saved?'true':'false';el.innerHTML=cardHTML(s);$('.shape-art',el).addEventListener('click',()=>openFocus(index));$$('button',el).forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();act(b.dataset.act,s,index)}));return el}
function filtered(){let a=state.shapes.slice();if(state.settings.archetype!=='all')a=a.filter(s=>s.archetypeId===state.settings.archetype);if(!state.settings.showRejected)a=a.filter(s=>state.decisions[s.id]?.rating!=='bad');const sort={recommended:(a,b)=>b.recommendation-a.recommendation,newest:(a,b)=>state.shapes.indexOf(a)-state.shapes.indexOf(b),table:(a,b)=>b.tableScore-a.tableScore,soul:(a,b)=>b.soulScore-a.soulScore,foot:(a,b)=>b.foot-a.foot,low:(a,b)=>a.height-b.height,saved:(a,b)=>Number(!!state.decisions[b.id]?.saved)-Number(!!state.decisions[a.id]?.saved)};return a.sort(sort[state.settings.sort]||sort.recommended)}
function empty(t,c){return`<div class="empty-state"><h3>${t}</h3><p>${c}</p></div>`}
function renderGallery(){const g=$('#galleryGrid');g.innerHTML='';const arr=filtered();if(!arr.length){g.innerHTML=empty('No silhouettes match the current filters.','Show rejected or generate a new batch.');return}const f=document.createDocumentFragment();arr.forEach(s=>f.appendChild(renderCard(s,state.shapes.indexOf(s))));g.appendChild(f)}
function renderShortlist(){const g=$('#shortlistGrid');g.innerHTML='';const saved=state.shapes.filter(s=>state.decisions[s.id]?.saved).sort((a,b)=>(state.decisions[b.id]?.tournamentWins||0)-(state.decisions[a.id]?.tournamentWins||0));if(!saved.length){g.innerHTML=empty('No saved silhouettes yet.','Use S or Save while browsing.');return}saved.forEach(s=>g.appendChild(renderCard(s,state.shapes.indexOf(s))))}
function renderTournament(){const st=$('#tournamentStage'),pool=state.shapes.filter(s=>state.decisions[s.id]?.saved||state.decisions[s.id]?.rating==='good');if(pool.length<2){st.innerHTML=empty('A/B needs at least two living candidates.','Mark a few forms Good or Save before starting the tournament.');return}const r=rng(Date.now()%1e6),a=pick(pool,r);let b=pick(pool,r);if(a.id===b.id)b=pool[(pool.indexOf(a)+1)%pool.length];st.innerHTML='';[a,b].forEach((s,i)=>{const el=document.createElement('article');el.className='tournament-card';el.innerHTML=`<div class="tournament-art">${svg(s,{large:true,scale:1.05})}</div><div><div class="eyebrow">${s.archetypeName}</div><h3>${i?'B':'A'} · ${s.id}</h3><p class="meta">${designerRead(s)}</p><button class="primary" style="width:100%; margin-top:14px">Choose ${i?'B':'A'}</button></div>`;$('button',el).addEventListener('click',()=>{const loser=i?a:b;setDecision(s.id,{rating:'good',saved:true,tournamentWins:(state.decisions[s.id]?.tournamentWins||0)+1});setDecision(loser.id,{tournamentLosses:(state.decisions[loser.id]?.tournamentLosses||0)+1});addHistory(s.id,'tournament-win',{against:loser.id});render()});st.appendChild(el)})}
function renderFamily(){const b=$('#familyBoard'),saved=state.shapes.filter(s=>state.decisions[s.id]?.saved).sort((a,b)=>b.recommendation-a.recommendation).slice(0,16);if(!saved.length){b.innerHTML=empty('Save candidates first.','Family Check translates each saved 330 ml DNA into 120 / 240 / 330 / 440.');return}b.innerHTML='';saved.forEach(s=>{const row=document.createElement('section');row.className='family-row';row.innerHTML=`<div class="family-header"><div><div class="eyebrow">${s.archetypeName}</div><h3>${s.id}</h3></div><button class="secondary" data-more>More like this</button></div>`;const grid=document.createElement('div');grid.className='family-grid';[120,240,330,440].forEach(ml=>{const ad=familyAdapt(s,ml),tile=document.createElement('div');tile.className='family-tile';tile.innerHTML=`<h4>${ml} ml</h4>${svg(s,{familySize:ml,scale:ml===120?1.18:ml===440?.88:1})}<p class="meta">H ${Math.round(ad.height)} · base ${Math.round(ad.base)} · rim ${Math.round(ad.rim)}</p><p class="risk ${ad.familyRisk>.55?'warn':''}">${familyRead(ad,ml)}</p>`;grid.appendChild(tile)});$('[data-more]',row).addEventListener('click',()=>moreLike(s));row.appendChild(grid);b.appendChild(row)})}
function familyRead(s,ml){if(ml===120&&s.familyRisk>.52)return'check: toy/instability risk';if(ml===440&&s.familyRisk>.52)return'check: bucket risk';if(s.campingRisk>.50)return'check: camping drift';if(s.tableScore>.70)return'good table presence';return'neutral adaptation'}
function renderFocus(s){$('#focusArt').innerHTML=svg(s,{large:true,scale:1.08});$('#focusArchetype').textContent=s.archetypeName;$('#focusTitle').textContent=s.id;$('#focusMeta').textContent=`H ${Math.round(s.height)} mm · base ${Math.round(s.base)} mm · rim ${Math.round(s.rim)} mm · stability ${s.stability} · score ${Math.round(s.recommendation*100)} · mass proxy ${s.massProxy}`;$('#focusRead').textContent=designerRead(s);const row=$('#tagRow');row.innerHTML='';critiqueTags.forEach(t=>{const b=document.createElement('button');b.className='tag';b.textContent=t;if((state.tags[s.id]||[]).includes(t))b.classList.add('active');b.addEventListener('click',()=>toggleTag(s.id,t));row.appendChild(b)});const d=state.decisions[s.id]||{};$('#focusGood').textContent=d.rating==='good'?'Good ✓':'Good';$('#focusBad').textContent=d.rating==='bad'?'Bad ✓':'Bad';$('#focusSave').textContent=d.saved?'Saved ✓':'Save'}
function designerRead(s){const a=[];if(s.tableScore>.76)a.push('strong table presence');if(s.soulScore>.76)a.push('visible soul without shouting');if(s.foot>.70)a.push('strong signature foot');if(s.foot<.28)a.push('weak foot: camping risk');if(s.lip>.70)a.push('expressive tulip rim');if(s.lip<.22)a.push('quiet rim, maybe too ordinary');if(s.waist>.58)a.push('clear waist tension');if(s.belly>.72)a.push('warm belly, family softness');if(s.hToRim>.98)a.push('taller mug energy');if(s.stability>.92)a.push('stable low table presence');if(s.campingRisk>.55)a.push('camping drift warning');return(a.length?a:['quiet balanced form']).join(' · ')+'.'}
function openFocus(i){state.focusIndex=clamp(i,0,state.shapes.length-1);renderFocus(state.shapes[state.focusIndex]);$('#focusDialog').showModal()} function closeFocus(){if($('#focusDialog').open)$('#focusDialog').close()}
function act(action,s){if(!s)return;if(action==='good'){setDecision(s.id,{rating:'good'});addHistory(s.id,'good')}if(action==='bad'){setDecision(s.id,{rating:'bad',saved:false});addHistory(s.id,'bad')}if(action==='save'){const saved=!state.decisions[s.id]?.saved;setDecision(s.id,{saved,rating:saved?(state.decisions[s.id]?.rating||'good'):state.decisions[s.id]?.rating});addHistory(s.id,saved?'save':'unsave')}if(action==='more'){moreLike(s);return}render();if($('#focusDialog').open)renderFocus(s)}
function setDecision(id,patch){state.decisions[id]={...(state.decisions[id]||{}),...patch,updatedAt:new Date().toISOString()};save()}
function addHistory(id,event,extra={}){state.history.push({id,event,at:new Date().toISOString(),...extra});save()}
function toggleTag(id,tag){const set=new Set(state.tags[id]||[]);set.has(tag)?set.delete(tag):set.add(tag);state.tags[id]=[...set];if(tag==='more like this')setDecision(id,{saved:true});addHistory(id,`tag:${tag}`);save();renderFocus(state.shapes[state.focusIndex]);render()}
function render(){ $$('.tab').forEach(t=>t.classList.toggle('active',t.dataset.view===state.view));$$('.view').forEach(v=>v.classList.remove('active'));$(`#${state.view}View`)?.classList.add('active');if(state.view==='gallery')renderGallery();if(state.view==='shortlist')renderShortlist();if(state.view==='tournament')renderTournament();if(state.view==='family')renderFamily();$('#viewTitle').textContent={gallery:'Find the form that has soul.',shortlist:'Return only to what still feels alive.',tournament:'Choose the stronger table object.',family:'Test whether the idea can become a family.'}[state.view];updateStats()}
function updateStats(){const v=Object.values(state.decisions);$('#countAll').textContent=filtered().length;$('#countSaved').textContent=v.filter(x=>x.saved).length;$('#countGood').textContent=v.filter(x=>x.rating==='good').length;$('#countBad').textContent=v.filter(x=>x.rating==='bad').length}
function exportFeedback(){download({schema:'shape-hunt-feedback-v2',exportedAt:new Date().toISOString(),project:'KonradLekawski/pottery-emaly-project',decisions:state.decisions,tags:state.tags,history:state.history,shapes:state.shapes,insight:insight()},`shape-hunt-feedback-${new Date().toISOString().slice(0,10)}.json`)}
function insight(){const good=state.shapes.filter(s=>state.decisions[s.id]?.rating==='good'||state.decisions[s.id]?.saved),bad=state.shapes.filter(s=>state.decisions[s.id]?.rating==='bad'),avg=(list,k)=>list.length?rnd(list.reduce((m,s)=>m+s[k],0)/list.length,3):null;return Object.fromEntries(['height','base','rim','belly','waist','foot','lip','shoulder','quiet','tableScore','soulScore','campingRisk'].map(k=>[k,{good:avg(good,k),bad:avg(bad,k)}]))}
function download(o,name){const blob=new Blob([JSON.stringify(o,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
function injectControls(){if($('#sortSelect'))return;const density=$('#densityRange').closest('.control-block'),block=document.createElement('div');block.className='control-block polish-controls';block.innerHTML=`<label for="sortSelect">Sort</label><select id="sortSelect"><option value="recommended">Recommended</option><option value="newest">Newest / generated order</option><option value="soul">Soul score</option><option value="table">Table presence</option><option value="foot">Strong foot</option><option value="low">Lower silhouettes</option><option value="saved">Saved first</option></select><label class="toggle-row"><input id="showRejected" type="checkbox"/> Show rejected</label><button id="clearRejectedBtn" class="ghost" type="button">Hide bad from this batch</button>`;density.after(block);$('#sortSelect').value=state.settings.sort;$('#showRejected').checked=state.settings.showRejected;$('#sortSelect').addEventListener('change',e=>{state.settings.sort=e.target.value;save();render()});$('#showRejected').addEventListener('change',e=>{state.settings.showRejected=e.target.checked;save();render()});$('#clearRejectedBtn').addEventListener('click',()=>{state.shapes=state.shapes.filter(s=>state.decisions[s.id]?.rating!=='bad');persistShapes();render();toast('Rejected silhouettes removed')});const toastEl=document.createElement('div');toastEl.id='toast';toastEl.className='toast';toastEl.setAttribute('aria-live','polite');document.body.appendChild(toastEl)}
function setup(){injectControls();const sel=$('#archetypeFilter');archetypes.forEach(a=>{const o=document.createElement('option');o.value=a.id;o.textContent=a.name;sel.appendChild(o)});sel.value=state.settings.archetype;sel.addEventListener('change',e=>{state.settings.archetype=e.target.value;save();render()});$('#densityRange').value=state.settings.density;$('#densityValue').textContent=state.settings.density;$('#densityRange').addEventListener('input',e=>{state.settings.density=+e.target.value;$('#densityValue').textContent=e.target.value;save()});$('#generateBtn').addEventListener('click',()=>generateBatch(+$('#densityRange').value));$('#exportBtn').addEventListener('click',exportFeedback);$('#resetBtn').addEventListener('click',()=>{if(!confirm('Reset all local decisions and tags?'))return;state.decisions={};state.tags={};state.history=[];save();render();toast('Decisions reset')});$('#closeFocus').addEventListener('click',closeFocus);$('#focusGood').addEventListener('click',()=>act('good',state.shapes[state.focusIndex]));$('#focusBad').addEventListener('click',()=>act('bad',state.shapes[state.focusIndex]));$('#focusSave').addEventListener('click',()=>act('save',state.shapes[state.focusIndex]));$('#focusMore').addEventListener('click',()=>act('more',state.shapes[state.focusIndex]));$$('.tab').forEach(t=>t.addEventListener('click',()=>{state.view=t.dataset.view;render()}));document.addEventListener('keydown',e=>{if(e.target&&['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName))return;const open=$('#focusDialog').open,s=state.shapes[state.focusIndex];if(e.key==='Escape'&&open)closeFocus();if(!open&&e.key===' '){e.preventDefault();const first=filtered()[0];if(first)openFocus(state.shapes.indexOf(first));return}if(!open)return;if(e.key==='g'||e.key==='G')act('good',s);if(e.key==='b'||e.key==='B')act('bad',s);if(e.key==='s'||e.key==='S')act('save',s);if(e.key==='m'||e.key==='M')act('more',s);if(e.key==='ArrowRight')moveFocus(1);if(e.key==='ArrowLeft')moveFocus(-1)});restoreShapes()?render():generateBatch(state.settings.density)}
function moveFocus(d){state.focusIndex=(state.focusIndex+d+state.shapes.length)%state.shapes.length;renderFocus(state.shapes[state.focusIndex])}
function toast(msg){const el=$('#toast');if(!el)return;el.textContent=msg;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2200)}
setup();